package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.projectFeatures.githubConnection
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            githubConnection {
                id = "PROJECT_EXT_4"
                displayName = "GitHub.com"
                clientId = "bc4d8127376a8dc776ae"
                clientSecret = "credentialsJSON:8a2e3799-eec6-4208-970f-c736f1b834c8"
            }
        }
    }
}
