package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'PetclinicVcs'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("PetclinicVcs")) {
    val expected = GitVcsRoot({
        id("PetclinicVcs")
        name = "PetclinicVcs"
        url = "https://github.com/thomato/spring-petclinic.git"
        param("useAlternates", "true")
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branch = "main"
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.USE_MIRRORS
    }

}
